Update check_pull.yml

diff --git a/.github/workflows/check_pull.yml b/.github/workflows/check_pull.yml
--- a/.github/workflows/check_pull.yml
+++ b/.github/workflows/check_pull.yml
@@ -17,23 +17,27 @@ jobs:
       - name: Get number of lines changed
         id: lines-changed
         run: |
-          # Calculate the number of lines changed
-          lines_changed=$(git diff --numstat HEAD^ | awk '{ total += $1 + $2 } END { print total }')
-          echo "::set-output name=lines_changed::$lines_changed"
+          # Check if this is the initial commit
+          if [ $(git rev-parse HEAD) = $(git rev-parse HEAD^) ]; then
+            echo "No previous commit found. Skipping lines changed calculation."
+            echo "::set-output name=lines_changed::0"
+          else
+            lines_changed=$(git diff --numstat HEAD^..HEAD | awk '{ total += $1 + $2 } END { print total }')
+            echo "Lines changed: $lines_changed"
+            echo "::set-output name=lines_changed::$lines_changed"
+          fi
 
       - name: Check if pull request is needed
         id: check-pr-needed
         run: |
-          # Get the number of lines changed from the previous step
           lines_changed=${{ steps.lines-changed.outputs.lines_changed }}
-          threshold=30 # I set it to 30, but we can change this if needed.
-          if [ "$lines_changed" -gt "$threshold" ]; then
-            echo "::set-output name=pr_needed::true"
-          else
-            echo "::set-output name=pr_needed::false"
+          threshold=30  # Adjust the threshold as needed
+          if [ -n "$lines_changed" ] && [ "$lines_changed" -gt "$threshold" ]; then
+            echo "::error::Changes exceed 30 lines. Please create a pull request for large changes."
+            exit 1  # Exit with non-zero code to indicate failure
           fi
 
-      - name: Comment on pull request if push was blocked
-        if: steps.check-pr-needed.outputs.pr_needed == 'true'
+      - name: Merge pull request if approved
+        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
         run: |
-          echo "::error::Push was blocked. Please create a pull request for large changes."
+          echo "::success::Pull request approved and merged. Changes can be pushed directly now."
